page:
  resource: '@PageBundle/Resources/config/routing.yml'

term:
  resource: '@TermBundle/Resources/config/routing.yml'

comment:
  resource: '@CommentBundle/Resources/config/routing.yml'

app:
  resource: '@AppBundle/Resources/config/routing.yml'