services:
  user.provider:
    class: UserBundle\Security\User\UserProvider
    arguments: ['@doctrine.orm.entity_manager']

  user.security.recover:
    class: UserBundle\Extend\Security\RecoverPassword
    arguments: ['@mailer', '@twig', '@doctrine.orm.entity_manager', '@router']